//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberBoss.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBoss.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quando o status for Cancelado, o valor deve ser 0..
        /// </summary>
        public static string AMOUNT_CANCELADO_INVALIDO {
            get {
                return ResourceManager.GetString("AMOUNT_CANCELADO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do faturamento não pode ser menor que 0..
        /// </summary>
        public static string AMOUNT_MINIMO {
            get {
                return ResourceManager.GetString("AMOUNT_MINIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do faturamento é obrigatório..
        /// </summary>
        public static string AMOUNT_OBRIGATORIO {
            get {
                return ResourceManager.GetString("AMOUNT_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do barbeiro deve ter no máximo 80 caracteres..
        /// </summary>
        public static string BARBER_NAME_MAXIMO {
            get {
                return ResourceManager.GetString("BARBER_NAME_MAXIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do barbeiro deve ter no mínimo 2 caracteres..
        /// </summary>
        public static string BARBER_NAME_MINIMO {
            get {
                return ResourceManager.GetString("BARBER_NAME_MINIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do barbeiro é obrigatório..
        /// </summary>
        public static string BARBER_NAME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("BARBER_NAME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobrança não encontrada..
        /// </summary>
        public static string BILLING_NOT_FOUND {
            get {
                return ResourceManager.GetString("BILLING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do cliente deve ter no máximo 120 caracteres..
        /// </summary>
        public static string CLIENT_NAME_MAXIMO {
            get {
                return ResourceManager.GetString("CLIENT_NAME_MAXIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do cliente deve ter no mínimo 2 caracteres..
        /// </summary>
        public static string CLIENT_NAME_MINIMO {
            get {
                return ResourceManager.GetString("CLIENT_NAME_MINIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do cliente é obrigatório..
        /// </summary>
        public static string CLIENT_NAME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CLIENT_NAME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do faturamento é obrigatória..
        /// </summary>
        public static string DATA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("DATA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As observações devem ter no máximo 500 caracteres..
        /// </summary>
        public static string NOTES_MAXIMO {
            get {
                return ResourceManager.GetString("NOTES_MAXIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O método de pagamento informado é inválido..
        /// </summary>
        public static string PAYMENT_METHOD_INVALIDO {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O método de pagamento é obrigatório..
        /// </summary>
        public static string PAYMENT_METHOD_OBRIGATORIO {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do serviço deve ter no máximo 120 caracteres..
        /// </summary>
        public static string SERVICE_NAME_MAXIMO {
            get {
                return ResourceManager.GetString("SERVICE_NAME_MAXIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do serviço deve ter no mínimo 2 caracteres..
        /// </summary>
        public static string SERVICE_NAME_MINIMO {
            get {
                return ResourceManager.GetString("SERVICE_NAME_MINIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do serviço é obrigatório..
        /// </summary>
        public static string SERVICE_NAME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("SERVICE_NAME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status informado é inválido..
        /// </summary>
        public static string STATUS_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status do faturamento é obrigatório..
        /// </summary>
        public static string STATUS_OBRIGATORIO {
            get {
                return ResourceManager.GetString("STATUS_OBRIGATORIO", resourceCulture);
            }
        }
    }
}
