//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberBoss.Domain.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceReportGenerationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceReportGenerationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBoss.Domain.Reports.ResourceReportGenerationMessages", typeof(ResourceReportGenerationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de Crédito.
        /// </summary>
        public static string CARTAO_CREDITO {
            get {
                return ResourceManager.GetString("CARTAO_CREDITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de débito.
        /// </summary>
        public static string CARTAO_DEBITO {
            get {
                return ResourceManager.GetString("CARTAO_DEBITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descricao.
        /// </summary>
        public static string DESCRICAO {
            get {
                return ResourceManager.GetString("DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinheiro.
        /// </summary>
        public static string DINHEIRO {
            get {
                return ResourceManager.GetString("DINHEIRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturamento da semana.
        /// </summary>
        public static string FATURAMENTO_DA_SEMANA {
            get {
                return ResourceManager.GetString("FATURAMENTO_DA_SEMANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outro.
        /// </summary>
        public static string OUTRO {
            get {
                return ResourceManager.GetString("OUTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pix.
        /// </summary>
        public static string PIX {
            get {
                return ResourceManager.GetString("PIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receita para.
        /// </summary>
        public static string RECEITA_PARA {
            get {
                return ResourceManager.GetString("RECEITA_PARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de pagamento.
        /// </summary>
        public static string TIPO_DE_PAGAMENTO {
            get {
                return ResourceManager.GetString("TIPO_DE_PAGAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string TITULO {
            get {
                return ResourceManager.GetString("TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string VALOR {
            get {
                return ResourceManager.GetString("VALOR", resourceCulture);
            }
        }
    }
}
